services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Circular\:
    resource: '../Classes/*'

  JWeiland\Circular\EventListener\AddPaginatorEventListener:
    tags:
    - name: event.listener
      event: JWeiland\Circular\Event\PostProcessFluidVariablesEvent
